nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  "@nrwl/cypress@14.2.4":
    dependencies:
      "nx": "14.2.4"
      "typescript": "~4.7.2"
  "@nrwl/jest@14.2.4":
    dependencies:
      "nx": "14.2.4"
      "typescript": "~4.7.2"
  "@nrwl/js@14.2.4":
    dependencies:
      "nx": "14.2.4"
  "@nrwl/linter@14.2.4":
    dependencies:
      "typescript": "~4.7.2"
  "@nrwl/next@14.2.4":
    dependencies:
      "@babel/core": "^7.18.5"
      "@types/node": "^17.0.42"
      "eslint": "^8.17.0"
      "nx": "14.2.4"
      "typescript": "~4.7.2"
      "webpack": "*"
  "@nrwl/react@14.2.4":
    dependencies:
      "eslint": "^8.17.0"
      "nx": "14.2.4"
  "@nrwl/storybook@14.2.4":
    dependencies:
      "nx": "14.2.4"
      "typescript": "~4.7.2"
      "webpack": "*"
  "@nrwl/web@14.2.4":
    dependencies:
      "@types/node": "^17.0.42"
      "nx": "14.2.4"
      "typescript": "~4.7.2"